name: python-template
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python>=3.6
  - pip
  - numpy
  - scipy
  - pandas
  - ipython
  - black
  - tqdm
  - click
  - matplotlib
  - scikit-learn
  - pytorch
  - pytest
  - yaml
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
