repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: debug-statements
        exclude: \{\{cookiecutter.repo_name\}\}/setup.py
      - id: name-tests-test
      - id: check-toml
      - id: forbid-new-submodules
      - id: requirements-txt-fixer
      - id: check-added-large-files
      - id: forbid-new-submodules
      - id: detect-private-key
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/pre-commit
    rev: v2.12.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ["-l 88"]
        exclude: \{\{cookiecutter.repo_name\}\}/setup.py
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.12.0
    hooks:
      - id: pyupgrade
        args: [--py36-plus]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.17.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        exclude: ^testing/resources/
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/awslabs/cfn-python-lint
    rev: v0.48.2
    hooks:
      - id: cfn-python-lint
        files: templates/*.yaml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.0.0
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        language: python
        types: [text]
        exclude: data
